In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('transaction_dataset.csv')

In [5]:
df = pd.DataFrame(data)

In [6]:
df.head()

,TransactionID,CustomerID,ProductID,ProductName,Quantity,PriceperUnit,Date,Region
0,TXN000001,CUST9935,4.0,Bread,1.0,175.0,1/3/2023,Galle
1,TXN000002,CUST2424,1.0,Pasta,14.0,121.0,1/4/2023,Galle
2,TXN000003,CUST7912,8.0,Pasta,9.0,102.0,3/16/2024,Kalutara
3,TXN000004,CUST1520,8.0,Yogurt,5.0,164.0,10/11/2024,Kalutara
4,TXN000005,CUST1488,10.0,Yogurt,20.0,175.0,5/8/2024,Matara

In [7]:
df.isnull().sum()

TransactionID    14
CustomerID       19
ProductID        15
ProductName      21
Quantity         26
PriceperUnit     28
Date             29
Region           18
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df.isnull().sum()

TransactionID    0
CustomerID       0
ProductID        0
ProductName      0
Quantity         0
PriceperUnit     0
Date             0
Region           0
dtype: int64

In [10]:
df.shape

(49946, 8)

In [11]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
49995    False
49996    False
49997    False
49998    False
49999    False
Length: 49946, dtype: bool

In [12]:
duplicates = df[df.duplicated()]
duplicates

Empty DataFrame
Columns: [TransactionID, CustomerID, ProductID, ProductName, Quantity, PriceperUnit, Date, Region]
Index: []

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())

In [15]:
df.head()

,TransactionID,CustomerID,ProductID,ProductName,Quantity,PriceperUnit,Date,Region
0,TXN000001,CUST9935,4.0,Bread,1.0,175.0,1/3/2023,Galle
1,TXN000002,CUST2424,1.0,Pasta,14.0,121.0,1/4/2023,Galle
2,TXN000003,CUST7912,8.0,Pasta,9.0,102.0,3/16/2024,Kalutara
3,TXN000004,CUST1520,8.0,Yogurt,5.0,164.0,10/11/2024,Kalutara
4,TXN000005,CUST1488,10.0,Yogurt,20.0,175.0,5/8/2024,Matara

In [16]:
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())

In [17]:
df.columns

Index(['TransactionID', 'CustomerID', 'ProductID', 'ProductName', 'Quantity',
       'PriceperUnit', 'Date', 'Region'],
      dtype='object')

In [18]:
df.head()

,TransactionID,CustomerID,ProductID,ProductName,Quantity,PriceperUnit,Date,Region
0,TXN000001,CUST9935,4.0,Bread,1.0,175.0,1/3/2023,Galle
1,TXN000002,CUST2424,1.0,Pasta,14.0,121.0,1/4/2023,Galle
2,TXN000003,CUST7912,8.0,Pasta,9.0,102.0,3/16/2024,Kalutara
3,TXN000004,CUST1520,8.0,Yogurt,5.0,164.0,10/11/2024,Kalutara
4,TXN000005,CUST1488,10.0,Yogurt,20.0,175.0,5/8/2024,Matara

In [19]:
df.head(10)

,TransactionID,CustomerID,ProductID,ProductName,Quantity,PriceperUnit,Date,Region
0,TXN000001,CUST9935,4.0,Bread,1.0,175.0,1/3/2023,Galle
1,TXN000002,CUST2424,1.0,Pasta,14.0,121.0,1/4/2023,Galle
2,TXN000003,CUST7912,8.0,Pasta,9.0,102.0,3/16/2024,Kalutara
3,TXN000004,CUST1520,8.0,Yogurt,5.0,164.0,10/11/2024,Kalutara
4,TXN000005,CUST1488,10.0,Yogurt,20.0,175.0,5/8/2024,Matara
5,TXN000006,CUST2535,10.0,Cheese,6.0,190.0,3/10/2023,Kalutara
6,TXN000007,CUST4582,8.0,Apple,6.0,175.0,1/25/2023,Colombo
7,TXN000008,CUST4811,6.0,Coffee,2.0,190.0,5/19/2023,Matara
8,TXN000009,CUST9279,2.0,Chicken,3.0,107.0,7/15/2024,Colombo
9,TXN000010,CUST1434,1.0,Cheese,6.0,427.0,7/2/2024,Matara

In [20]:
df.loc[150:200]

,TransactionID,CustomerID,ProductID,ProductName,Quantity,PriceperUnit,Date,Region
150,TXN000151,CUST4470,1.0,Pasta,16.0,427.0,10/12/2023,Galle
151,TXN000152,CUST9835,3.0,Yogurt,14.0,377.0,12/5/2024,Colombo
152,TXN000153,CUST4295,4.0,Milk,16.0,102.0,8/15/2024,Galle
153,TXN000154,CUST6107,9.0,Bread,5.0,62.0,1/7/2024,Galle
154,TXN000155,CUST7537,9.0,Chicken,5.0,175.0,5/24/2024,Colombo
155,TXN000156,CUST7118,4.0,Fish,20.0,62.0,11/3/2024,Kalutara
156,TXN000157,CUST8177,7.0,Bread,16.0,121.0,8/9/2024,Matara
157,TXN000158,CUST9479,10.0,Pasta,15.0,121.0,4/16/2024,Colombo
158,TXN000159,CUST8397,8.0,Pasta,8.0,102.0,4/17/2023,Matara
159,TXN000160,CUST2982,1.0,Coffee,6.0,190.0,5/25/2023,Galle
160,TXN000161,CUST5061,3.0,Bread,2.0,121.0,5/4/2023,Matara
161,TXN000162,CUST4681,6.0,Rice,12.0,377.0,10/7/2024,Colombo
162,TXN000163,CUST2049,8.0,Pasta,17.0,121.0,9/18/2024,Galle
163,TXN000164,CUST6539,10.0,Apple,4.0,107.0,4/14/2023,Kalutara
164,TXN000165,CUST1344,6.0,Cheese,11.0,121.0,3/24/2023,Galle
165,TXN000166,CUST4770,4.0,Rice,15.0,429.0,2/18/2024,Matara
166,TXN000167,CUST4608,6.0,Cheese,2.0,62.0,1/26/2023,Matara
167,TXN000168,CUST1117,7.0,Fish,17.0,62.0,6/24/2024,Colombo
168,TXN000169,CUST2163,5.0,Chicken,12.0,62.0,9/29/2023,Galle
169,TXN000170,CUST1964,5.0,Chicken,2.0,62.0,11/12/2024,Kalutara
170,TXN000171,CUST4750,2.0,Yogurt,7.0,175.0,8/7/2024,Matara
171,TXN000172,CUST2104,2.0,Rice,16.0,107.0,12/27/2023,Kalutara
172,TXN000173,CUST1514,10.0,Cheese,3.0,377.0,12/29/2024,Kalutara
173,TXN000174,CUST6413,4.0,Coffee,14.0,190.0,11/23/2023,Matara
174,TXN000175,CUST2160,6.0,Chicken,8.0,121.0,5/20/2023,Matara
175,TXN000176,CUST9423,5.0,Apple,6.0,190.0,1/10/2024,Galle
176,TXN000177,CUST4899,8.0,Fish,9.0,175.0,1/30/2024,Colombo
177,TXN000178,CUST5562,3.0,Cheese,9.0,62.0,9/11/2023,Kalutara
178,TXN000179,CUST8953,9.0,Rice,20.0,190.0,9/12/2023,Kalutara
179,TXN000180,CUST4510,7.0,Pasta,5.0,429.0,11/2/2023,Matara
180,TXN000181,CUST9834,4.0,Rice,9.0,429.0,3/11/2023,Galle
181,TXN000182,CUST3167,10.0,Apple,10.0,175.0,12/16/2024,Colombo
182,TXN000183,CUST8744,10.0,Apple,7.0,175.0,8/29/2023,Galle
183,TXN000184,CUST4981,7.0,Fish,18.0,190.0,7/23/2024,Kalutara
184,TXN000185,CUST8749,3.0,Yogurt,5.0,164.0,4/3/2024,Colombo
185,TXN000186,CUST7669,5.0,Fish,10.0,121.0,8/2/2023,Matara
186,TXN000187,CUST4119,1.0,Cheese,20.0,190.0,4/26/2023,Matara
187,TXN000188,CUST2545,3.0,Apple,19.0,427.0,5/3/2024,Kalutara
188,TXN000189,CUST2588,4.0,Coffee,7.0,175.0,6/26/2023,Galle
189,TXN000190,CUST8062,9.0,Bread,16.0,121.0,11/16/2023,Galle
190,TXN000191,CUST6804,5.0,Cheese,1.0,175.0,4/8/2023,Colombo
191,TXN000192,CUST7939,10.0,Apple,9.0,102.0,3/9/2024,Matara
192,TXN000193,CUST7735,3.0,Fish,6.0,102.0,2/27/2023,Kalutara
193,TXN000194,CUST8651,1.0,Rice,13.0,427.0,3/19/2024,Matara
194,TXN000195,CUST1887,4.0,Apple,18.0,121.0,7/21/2023,Matara
195,TXN000196,CUST2612,2.0,Chicken,19.0,427.0,3/14/2024,Colombo
196,TXN000197,CUST1993,8.0,Bread,8.0,175.0,8/24/2023,Kalutara
197,TXN000198,CUST7596,6.0,Yogurt,8.0,427.0,11/5/2023,Kalutara
198,TXN000199,CUST6559,10.0,Pasta,15.0,164.0,7/12/2023,Matara
199,TXN000200,CUST2790,2.0,Pasta,18.0,107.0,3/14/2023,Colombo
200,TXN000201,CUST5073,5.0,Cheese,20.0,102.0,8/19/2023,Galle

In [21]:
df.loc[20]

TransactionID    TXN000021
CustomerID        CUST5552
ProductID              4.0
ProductName          Bread
Quantity              17.0
PriceperUnit         427.0
Date             8/28/2024
Region              Matara
Name: 20, dtype: object

In [22]:
df.iloc[[19, 59, 79]]

,TransactionID,CustomerID,ProductID,ProductName,Quantity,PriceperUnit,Date,Region
19,TXN000020,CUST6574,3.0,Pasta,10.0,62.0,3/17/2023,Galle
59,TXN000060,CUST5010,6.0,Milk,12.0,121.0,6/9/2023,Galle
79,TXN000080,CUST3340,5.0,Fish,11.0,121.0,12/28/2023,Galle

In [23]:
df.iloc[50:72:3, 0:2]

   TransactionID CustomerID
50     TXN000051   CUST6977
53     TXN000054   CUST6820
56     TXN000057   CUST2169
59     TXN000060   CUST5010
62     TXN000063   CUST7216
65     TXN000066   CUST6313
68     TXN000069   CUST1525
71     TXN000072   CUST5386

In [24]:
df.loc[[19, 59 ,79], ['ProductID', 'ProductName']]

    ProductID ProductName
19        3.0       Pasta
59        6.0        Milk
79        5.0        Fish

In [25]:
df.head()

,TransactionID,CustomerID,ProductID,ProductName,Quantity,PriceperUnit,Date,Region
0,TXN000001,CUST9935,4.0,Bread,1.0,175.0,1/3/2023,Galle
1,TXN000002,CUST2424,1.0,Pasta,14.0,121.0,1/4/2023,Galle
2,TXN000003,CUST7912,8.0,Pasta,9.0,102.0,3/16/2024,Kalutara
3,TXN000004,CUST1520,8.0,Yogurt,5.0,164.0,10/11/2024,Kalutara
4,TXN000005,CUST1488,10.0,Yogurt,20.0,175.0,5/8/2024,Matara

In [26]:
df.drop('ProductID', axis=1)

,TransactionID,CustomerID,ProductName,Quantity,PriceperUnit,Date,Region
0,TXN000001,CUST9935,Bread,1.0,175.0,1/3/2023,Galle
1,TXN000002,CUST2424,Pasta,14.0,121.0,1/4/2023,Galle
2,TXN000003,CUST7912,Pasta,9.0,102.0,3/16/2024,Kalutara
3,TXN000004,CUST1520,Yogurt,5.0,164.0,10/11/2024,Kalutara
4,TXN000005,CUST1488,Yogurt,20.0,175.0,5/8/2024,Matara
...,...,...,...,...,...,...,...
49995,TXN049996,CUST7032,Apple,19.0,175.0,6/21/2024,Galle
49996,TXN049997,CUST5120,Cheese,13.0,164.0,2/6/2024,Colombo
49997,TXN049998,CUST8567,Chicken,6.0,429.0,8/29/2024,Galle
49998,TXN049999,CUST8061,Cheese,20.0,175.0,12/10/2023,Colombo
49999,TXN050000,CUST7231,Apple,6.0,107.0,5/31/2024,Galle

In [27]:
df.drop('ProductID', axis=1, inplace=True)

In [28]:
df.drop(columns=['Date'], inplace=True)

In [29]:
df.drop([5], axis=0, inplace=True)

In [30]:
df.head()

  TransactionID CustomerID ProductName  Quantity  PriceperUnit    Region
0     TXN000001   CUST9935       Bread       1.0         175.0     Galle
1     TXN000002   CUST2424       Pasta      14.0         121.0     Galle
2     TXN000003   CUST7912       Pasta       9.0         102.0  Kalutara
3     TXN000004   CUST1520      Yogurt       5.0         164.0  Kalutara
4     TXN000005   CUST1488      Yogurt      20.0         175.0    Matara

In [31]:
df.drop(df.index[1:7], inplace=True)

In [32]:
df.dropna(inplace=True)

In [36]:
df.to_csv('cleaned file.csv')

In [39]:
df.to_excel('cleaned 2.xlsx')