In [1]:
dic = {
    'name': ['John', 'Anne', 'Harry'],
    "age": [25, 22, 21],
    'gender': ['Male', 'Female', 'Male']
}

In [3]:
print(dic)

{'name': ['John', 'Anne', 'Harry'], 'age': [25, 22, 21], 'gender': ['Male', 'Female', 'Male']}

In [4]:
import pandas as pd

df = pd.DataFrame(dic)

In [5]:
df.sort_values(by='name', inplace=True)

In [6]:
df

    name  age  gender
1   Anne   22  Female
2  Harry   21    Male
0   John   25    Male

In [7]:
new_dic = {
    'StudentID': [47, 14, 78, 45, 15],
    'Name': ["Alice", "Bob", "Charli", "David", "Eve"],
    'PCP Score': [95, 85, 75, 65, 55],
    'BPS Score': [85, 75, 65, 55, 45],
    'DDD Score': [180, 160, 140, 120, 100]
}

In [8]:
new_df = pd.DataFrame(new_dic)
new_df

   StudentID    Name  PCP Score  BPS Score  DDD Score
0         47   Alice         95         85        180
1         14     Bob         85         75        160
2         78  Charli         75         65        140
3         45   David         65         55        120
4         15     Eve         55         45        100

In [9]:
new_df.sort_values(by='StudentID', inplace=True)
new_df

   StudentID    Name  PCP Score  BPS Score  DDD Score
1         14     Bob         85         75        160
4         15     Eve         55         45        100
3         45   David         65         55        120
0         47   Alice         95         85        180
2         78  Charli         75         65        140

In [20]:
third_df = new_df.sort_values(by=["StudentID", "Name"], ascending=[False, False])

In [21]:
third_df

   StudentID    Name  PCP Score  BPS Score  DDD Score
2         78  Charli         75         65        140
0         47   Alice         95         85        180
3         45   David         65         55        120
4         15     Eve         55         45        100
1         14     Bob         85         75        160

In [24]:
third_df['Total Score'] = third_df['PCP Score'] + third_df['BPS Score'] + third_df['DDD Score']

In [25]:
third_df

   StudentID    Name  PCP Score  BPS Score  DDD Score  Total  Total Score
2         78  Charli         75         65        140    280          280
0         47   Alice         95         85        180    360          360
3         45   David         65         55        120    240          240
4         15     Eve         55         45        100    200          200
1         14     Bob         85         75        160    320          320