In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('transaction_dataset.csv')

In [4]:
df = pd.DataFrame(data)

In [5]:
df.head()

,TransactionID,CustomerID,ProductID,ProductName,Quantity,PriceperUnit,Date,Region
0,TXN000001,CUST9935,4.0,Bread,1.0,175.0,1/3/2023,Galle
1,TXN000002,CUST2424,1.0,Pasta,14.0,121.0,1/4/2023,Galle
2,TXN000003,CUST7912,8.0,Pasta,9.0,102.0,3/16/2024,Kalutara
3,TXN000004,CUST1520,8.0,Yogurt,5.0,164.0,10/11/2024,Kalutara
4,TXN000005,CUST1488,10.0,Yogurt,20.0,175.0,5/8/2024,Matara

In [6]:
grouped_value = df.groupby('Region')['Quantity'].sum()
grouped_value

Region
Colombo     130945.0
Galle       128556.0
Kalutara    133073.0
Matara      131328.0
Name: Quantity, dtype: float64

In [7]:
grouped_value = df.groupby('Region')[['Quantity', 'PriceperUnit']].sum()
grouped_value

          Quantity  PriceperUnit
Region
Colombo   130945.0     2694571.0
Galle     128556.0     2679230.0
Kalutara  133073.0     2719391.0
Matara    131328.0     2647952.0

In [13]:
sortedGroupValue = grouped_value.sort_values(['Quantity', 'PriceperUnit'], ascending=True)

In [14]:
sortedGroupValue

          Quantity  PriceperUnit
Region
Galle     128556.0     2679230.0
Colombo   130945.0     2694571.0
Matara    131328.0     2647952.0
Kalutara  133073.0     2719391.0

In [ ]:
grouped_value = df.groupby('Region')[['Quantity', 'PriceperUnit', 'CustomerID']].[sum(), 'count']
grouped_value